# Generated by Django 3.2 on 2022-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=500)),
                ('Genre', models.CharField(max_length=500)),
                ('Favorite', models.BooleanField(default=True)),
            ],
        ),
    ]
